### ISSUE TITLE
noxmoe主题页面显示不正常，其他两种模式正常，请问一下，如何解决，谢谢！

### ISSUE THREAD

**Issue by b1ncoder** [Mintimate/OneindexM#6]
![uTools_1662468995081](https://user-images.githubusercontent.com/74662269/188641382-6540aa8e-f494-468a-8ef4-d52375776f65.png)

**Comment by Mintimate** [comment]
没有内置叫`noxmoe`的主题.其他主题如果出现类似情况，自行查看F12;并检查CDN资源加载情况，如无法加载，自行前往主题文件内替换(`OneindexM/tree/master/view/themes`)

**Comment by b1ncoder** [comment]
新手，我直接把整个代码全上传到服务器了，后台管理界面里面有noxmoe这个主题可选，我也对了一下服务器上主题文件夹里面noxmoe的内容和GitHub上面的是完全一致的，能劳烦大佬详细说明一下替换那一个或者一些文件吗？感谢！
